version: "3.9"

services:
  fpm:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
